server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/event_platform}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
jwt:
  issuer: event-platform
  secret: ${JWT_SECRET:81ad58d0-eea6-44a0-a765-a8fb8b2e39c1}
  expires-in: ${JWT_EXPIRES_IN:86400}